// Banco de retos semanales. Cada jornada se sortean 3 de aquí para votar
// cuál cumplirá el último de la liga. Mismo tono que el resto de la app:
// informal, banter, tareas públicas y humillantes pero sanas entre amigos.
export const CHALLENGES_DB = [
  { title: "Outfit de Despedido", description: "Subir foto al grupo vistiendo la ropa más hortera posible simulando despido. Plazo: 48h." },
  { title: "Comentarista Mudo", description: "Grabar vídeo justificando la derrota solo con mímica sin emitir sonido. Plazo: 48h." },
  { title: "El Cantante de WhatsApp", description: "Grabar un audio de WhatsApp de 1 minuto cantando a capela una balada a tu peor jugador." },
  { title: "Rueda de Prensa del Desastre", description: "Grabar una rueda de prensa de 1 minuto explicando 'la crisis del club' con cara muy seria. Plazo: 48h." },
  { title: "El Horóscopo del Colista", description: "Escribir el horóscopo semanal del grupo como si fueras un astrólogo, culpando a los planetas de tu derrota." },
  { title: "Anuncio de Fichaje Falso", description: "Grabar un vídeo 'anunciando' el fichaje de un jugador random como si fuera tu club, con música dramática." },
  { title: "El Podcast de la Vergüenza", description: "Mandar un audio de 90 segundos analizando tu propia jornada como si fueras un tertuliano de radio deportiva." },
  { title: "Firma de Autógrafos", description: "Grabarte firmando 'autógrafos' imaginarios en la calle o en casa, muy serio, durante 30 segundos." },
  { title: "El Llanto en Directo", description: "Mandar una nota de voz llorando (fingido) de 20 segundos explicando por qué eres el peor mánager de la liga." },
  { title: "Camiseta al Revés 24h", description: "Llevar puesta la camiseta de tu equipo (o cualquiera) del revés durante todo un día y mandar 3 fotos como prueba." },
  { title: "El Meme Personalizado", description: "Crear un meme con tu propia cara sobre tu derrota y ponerlo de foto de perfil 24h." },
  { title: "Disculpa Pública en Verso", description: "Escribir una disculpa de 6 versos al grupo por tu actuación de la jornada, en rima." },
  { title: "El Reportero de Guerra", description: "Grabar un vídeo narrando tu derrota como si fuera un parte de guerra, con casco o gorro improvisado." },
  { title: "Contestador Personalizado", description: "Cambiar el saludo de voz de tu WhatsApp (nota fijada) admitiendo que eres el farolillo rojo, durante 48h." },
  { title: "El Photocall de la Derrota", description: "Montar un 'photocall' casero con cartel de tu peor jugador y hacerte una foto posando delante." },
  { title: "Baile de la Resignación", description: "Grabar 15 segundos bailando cualquier canción con la cara más triste y resignada posible." },
  { title: "El Traductor Simultáneo", description: "Grabar un audio 'traduciendo' al inglés (mal, exagerado) los insultos que te manda el grupo." },
  { title: "Carta a mi Yo del Pasado", description: "Escribir una carta de 5 líneas a ti mismo antes de hacer la alineación, explicando en qué te equivocaste." },
  { title: "El Comentarista Ciego", description: "Narrar en audio los mejores goles de la jornada sin haber visto ninguno, inventándotelo todo." },
  { title: "Estado de Perfil Castigado", description: "Poner como foto de perfil de WhatsApp una imagen elegida por el ganador de la semana, durante 24h." },
  { title: "El Discurso de Dimisión", description: "Grabar un vídeo de 30 segundos 'dimitiendo' como mánager con tono muy dramático, estilo rueda de prensa." },
  { title: "Sopa de Letras Viviente", description: "Mandar una foto formando con el cuerpo (o con objetos) la inicial de tu peor jugador de la jornada." },
  { title: "El Sommelier del Fracaso", description: "Grabar un audio 'catando' un vaso de agua como si fuera vino, describiendo el sabor de tu derrota." },
  { title: "Anuncio de Publicidad", description: "Grabar un anuncio de 20 segundos vendiéndote a ti mismo como 'el peor fichaje de la historia'." },
  { title: "El Profeta Fallido", description: "Mandar una predicción por escrito de cómo te irá la próxima jornada, exagerada al estilo vidente de feria." },
  { title: "Selfie de la Vergüenza", description: "Mandar un selfie nada más levantarte con la peor cara posible y el texto 'así me siento tras esta jornada'." },
  { title: "El Speaker del Estadio", description: "Grabar un audio anunciando tu propia alineación como si fueras el speaker de un estadio, con eco y todo." },
  { title: "Carta al Bote", description: "Escribir una carta de amor de 4 líneas dirigida al bote de la liga, jurando que la próxima jornada será distinto." },
  { title: "El Retrato del Colista", description: "Dibujar (mal, a mano) al ganador de la jornada como si fuera un héroe, y mandar la foto al grupo." },
  { title: "Playback Trágico", description: "Grabar un playback exagerado de una canción triste dedicándosela a tu equipo." },
  { title: "El Titular de Prensa", description: "Escribir el titular que pondría un periódico deportivo sobre tu jornada, cuanto más ridículo mejor." },
  { title: "Cuenta Atrás Pública", description: "Publicar una historia contando los días que faltan para 'redimirte' en la próxima jornada." },
  { title: "El Photobomb Obligado", description: "Colarte (con permiso) en una foto de otro miembro del grupo esta semana y mandarla como prueba." },
  { title: "Monólogo de Humor Negro", description: "Grabar 30 segundos de 'monólogo' haciendo comedia sobre tu propia mala jornada." },
];
